name: Codecov Workflow

on: [push]

jobs:

  test:
    name: Run Tests and Codecov
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8, 3.9]
        os: [windows-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Python Poetry
        uses: abatilo/actions-poetry@v2.1.0
      - name: Install dependencies
        run: |
          poetry --version
          poetry install
          poetry show
      - name: Generate coverage report
        run: |
          poetry run pytest --cov=version_helper --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          name: codecov-umbrella
#          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          verbose: true

  publish:
    name: Build and Publish Package
    needs: [test]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
      - name: Setup Python Poetry
        uses: abatilo/actions-poetry@v2.1.0
      - name: Install Dependencies
        run: |
          poetry --version
          poetry install
          poetry show
      - name: Configure PyPI Credentials
        run: |
          - poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
      - name: Build Package
        run: poetry build
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Package
        run: poetry publish
